import Navbar from '../components/Navbar';
import Head from 'next/head'
import styles from './Layout.module.css';

export default function Layout({ children }){
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
            </Head>

            <Navbar/>

            <div className={styles.children}>
                {children}
            </div>

        </div>
    )
}